name: "windows"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test-windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update environment variables
      # See:
      #   - On Bazel cache: https://docs.bazel.build/versions/master/output_directories.html
      #   - On problems with `tar.exe`: https://github.com/actions/toolkit/issues/632
      #   - For symlinking: https://www.joshkel.com/2018/01/18/symlinks-in-windows/
      run: |
        echo "BAZEL_CACHE_DIR=$env:USERPROFILE\_bazel_$env:USERNAME" >> $env:GITHUB_ENV
        echo "MSYS=winsymlinks:nativestrict" >> $env:GITHUB_ENV
        echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH

    # TODO: Disabling the cache for now. Generated cache has broken
    # symlinks, which breaks the build.
    #
    #- name: Mount bazel cache
    #  uses: actions/cache@v2
    #  with:
    #    path: ${{ env.BAZEL_CACHE_DIR}}
    #    key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE.bazel') }}
    #    restore-keys: ${{ runner.os }}-bazel

    - name: Install bazelisk
      run: |
        powershell Invoke-WebRequest https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-windows-amd64.exe -OutFile bazel.exe

    - name: Build
      run: ./bazel.exe build -c opt //mozolm/...

    - name: Test
      run: ./bazel.exe test -c opt //mozolm/...
